apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-demo-dev
data:
  # property-like keys; each key maps to a simple value
  dev-level: "development"
  level_properties_file_name: "devops.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
