apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-working-host-das-django
  namespace: django-todo-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/allow-snippet-annotations: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: django-todo-example-info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-todo-service
                port:
                  number: 8001

