apiVersion: v1
kind: Service
metadata:
  name: django-todo-service
  namespace: django-todo-app 
spec:
  selector:
    app.kubernetes.io/name: django-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 9376

